development:
  app_id: K6pC2i5fMybC0Zmk3pEicIOGRcJ3uKQ6l6W1sXUf
  master_key: JQjR9zu3Y9V8PcRFWWVkDqQTA9mrf2XOM1ogc7Re

test:
  app_id: K6pC2i5fMybC0Zmk3pEicIOGRcJ3uKQ6l6W1sXUf
  master_key: JQjR9zu3Y9V8PcRFWWVkDqQTA9mrf2XOM1ogc7Re

production:
  app_id: K6pC2i5fMybC0Zmk3pEicIOGRcJ3uKQ6l6W1sXUf
  master_key: JQjR9zu3Y9V8PcRFWWVkDqQTA9mrf2XOM1ogc7Re
