development:
  app_id: K6pC2i5fMybC0Zmk3pEicIOGRcJ3uKQ6l6W1sXUf
  master_key: r1CIefQ2Lx8uCtgojreyESZvvheEafjRDp0j7NDV

test:
  app_id: K6pC2i5fMybC0Zmk3pEicIOGRcJ3uKQ6l6W1sXUf
  master_key: r1CIefQ2Lx8uCtgojreyESZvvheEafjRDp0j7NDV

production:
  app_id: K6pC2i5fMybC0Zmk3pEicIOGRcJ3uKQ6l6W1sXUf
  master_key: r1CIefQ2Lx8uCtgojreyESZvvheEafjRDp0j7NDV
